# Generated by Django 2.1.3 on 2018-12-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_budget_approval_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget_approval',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
