# Generated by Django 2.1.3 on 2018-12-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_budget_approval_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget_approval',
            old_name='no',
            new_name='number',
        ),
    ]
