# Generated by Django 2.1.3 on 2018-12-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20181203_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget_approval',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
