# Generated by Django 2.1.3 on 2018-12-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20181203_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reimbursement_form',
            old_name='paid_to',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='reimbursement_form',
            old_name='sub_total',
            new_name='subtotal',
        ),
        migrations.RemoveField(
            model_name='reimbursement_form',
            name='name',
        ),
        migrations.AlterField(
            model_name='budget_approval',
            name='delivery_due_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='budget_approval',
            name='number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='budget_approval',
            name='product',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='budget_approval',
            name='purpose',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='budget_approval',
            name='quantity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='budget_approval',
            name='remark',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='budget_approval',
            name='request_approval_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='budget_approval',
            name='request_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='budget_approval',
            name='spec',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='budget_approval',
            name='total',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='budget_approval',
            name='total_price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='budget_approval',
            name='unit_price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='budget_approval',
            name='ventor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
