# Generated by Django 2.1.3 on 2018-12-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20181203_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryBudgetApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('purpose', models.CharField(blank=True, max_length=50)),
                ('request_date', models.CharField(blank=True, max_length=50)),
                ('request_approval_date', models.CharField(blank=True, max_length=50)),
                ('delivery_due_date', models.CharField(blank=True, max_length=50)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('ventor', models.CharField(blank=True, max_length=50)),
                ('product', models.CharField(blank=True, max_length=50)),
                ('spec', models.CharField(blank=True, max_length=50)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('unit_price', models.CharField(blank=True, max_length=50)),
                ('total_price', models.CharField(blank=True, max_length=50)),
                ('remark', models.CharField(blank=True, max_length=50)),
                ('total', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
