# Generated by Django 2.1.3 on 2019-01-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_temporary_purchase_order_temporary_reimbursement_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement_form',
            name='amount',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reimbursement_form',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reimbursement_form',
            name='detail',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reimbursement_form',
            name='item',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reimbursement_form',
            name='paid',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reimbursement_form',
            name='payment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reimbursement_form',
            name='remark',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reimbursement_form',
            name='subtotal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reimbursement_form',
            name='total',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
